import {db,check,uploadDocument,downloadDocument,removeDocument} from './operator-api.js';
import {coverage,acknowledgements,emptyProfile,editable,escapeHtml as h,documentSlots,missingItems,renewalIssues,renderRecord} from './operator-data.js';
import {AGREEMENT_VERSION} from './operator-config.js';
import './select.js';
const root=document.querySelector('#app'),steps=['Business','Equipment & operators','Insurance','Documents','Review & submit'];
let user,app,profile,docs=[],step=0,mode='signup',busy=false,dirty=false,message='',errorMessage='',reviewer=false,recovering=false;
const get=(obj,path)=>path.split('.').reduce((a,k)=>a?.[k],obj)??'';
const set=(obj,path,value)=>{const parts=path.split('.');let cur=obj;for(const k of parts.slice(0,-1))cur=cur[k]??=(/^\d+$/.test(k)?[]:{});cur[parts.at(-1)]=value;};
const statusLabel={draft:'Draft',submitted:'In review',changes_requested:'Updates requested',approved:'Approved',declined:'Not approved'};
function notice(){return `<div id="op-message" role="status" aria-live="polite">${message?`<p class="notice success">${h(message)}</p>`:''}</div><div role="alert">${errorMessage?`<p class="notice error">${h(errorMessage)}</p>`:''}</div>`;}
function field(path,label,type='text',options){const v=get(profile,path),id=path.replaceAll('.','-');return `<label class="field" for="${id}"><span>${label}</span>${options?`<select id="${id}" data-field="${path}"><option value="">Select…</option>${options.map(x=>`<option ${v===x?'selected':''}>${h(x)}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="${id}" data-field="${path}" rows="3" maxlength="3000">${h(v)}</textarea>`:`<input id="${id}" data-field="${path}" type="${type}" value="${h(v)}" ${type==='number'?'min="0" step="any"':''} ${type==='date'?'':'maxlength="300"'}>`}</label>`;}
function authView(){
 const reset=mode==='reset',signingIn=mode==='signin'&&!recovering;
 root.innerHTML=`<section class="op-welcome"><section class="auth-card" aria-labelledby="auth-heading"><h1 id="auth-heading">${recovering?'New password':reset?'Reset password':signingIn?'Operator sign in':'Operator signup'}</h1>${notice()}<form id="auth-form">${!recovering?'<label class="field"><span>Email address</span><input name="email" type="email" required autocomplete="email" placeholder="you@yourbusiness.com" maxlength="254"></label>':''}${!reset?`<label class="field"><span>${signingIn?'Password':'Password (12+ characters)'}</span><input name="password" type="password" required ${signingIn?'':'minlength="12"'} maxlength="128" autocomplete="${signingIn?'current-password':'new-password'}"></label>`:''}${mode==='signup'&&!recovering?'<label class="check"><input name="privacy" type="checkbox" required><span>I’ve read the <a href="/operator-privacy.html" target="_blank" rel="noopener">privacy notice</a>.</span></label>':''}<button class="btn wide" ${busy?'disabled':''}>${busy?'Please wait…':recovering?'Update password':reset?'Send reset link':signingIn?'Sign in':'Create account'} <span aria-hidden="true">→</span></button></form>${!recovering?reset?'<p class="auth-switch"><button data-mode="signin" class="text-btn">Back to sign in</button></p>':`<p class="auth-switch">${signingIn?'New to LiftCrew?':'Already registered?'} <button data-mode="${signingIn?'signup':'signin'}" class="text-btn">${signingIn?'Create account':'Sign in'}</button></p>${signingIn?'<div class="auth-links"><button class="text-btn" data-mode="reset">Forgot password?</button><button class="text-btn" data-resend>Resend confirmation</button></div>':''}`:''}</section></section>`;
 root.querySelector('#auth-form').onsubmit=authSubmit;
 root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;message='';errorMessage='';authView();});
 root.querySelector('[data-resend]')?.addEventListener('click',resend);
}
async function authSubmit(event){event.preventDefault();if(busy)return;const f=new FormData(event.target),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');busy=true;errorMessage='';message='';event.submitter.disabled=true;event.submitter.textContent='Please wait…';try{
 if(recovering){check(await db.auth.updateUser({password}));recovering=false;message='Password updated.';await loadApplication();return;}
 if(mode==='reset'){check(await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/operators.html'}));message='If an account exists, a password reset email will be sent. Check your inbox and spam folder.';}
 else if(mode==='signup'){const data=check(await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/operators.html'}}));if(data.session){user=data.user;await loadApplication();return;}message='Check your email to confirm your account, then return here to sign in. If it does not arrive, contact your LiftCrew representative.';mode='signin';}
 else{const data=check(await db.auth.signInWithPassword({email,password}));user=data.user;await loadApplication();return;}
 }catch(e){app=null;errorMessage=e.message||'Unable to connect. Please try again.';}finally{busy=false;if(!app||recovering)authView();}}
async function resend(){const email=root.querySelector('[name=email]')?.value.trim();if(!email){errorMessage='Enter your email address first.';authView();return;}try{check(await db.auth.resend({type:'signup',email,options:{emailRedirectTo:location.origin+'/operators.html'}}));message='Confirmation requested. Check your email; delivery depends on account status.';errorMessage='';}catch(e){errorMessage=e.message;}authView();}
async function loadApplication(){
 const verified=check(await db.auth.getUser());user=verified.user;
 if(!user)throw Error('Please sign in again.');
 app=check(await db.from('operator_applications').select('*').eq('user_id',user.id).maybeSingle());
 if(!app){const insert=await db.from('operator_applications').insert({user_id:user.id,profile:emptyProfile()}).select().single();if(insert.error?.code==='23505')app=check(await db.from('operator_applications').select('*').eq('user_id',user.id).single());else app=check(insert);}
 profile=structuredClone(app.profile);profile.business??={};profile.equipment??=[];profile.operators??=[];profile.insurance??={};
 docs=check(await db.from('operator_documents').select('*').eq('application_id',app.id).order('created_at'));
 reviewer=check(await db.rpc('is_operator_reviewer'))===true;dirty=false;render();
}
function business(){return `<h2>Business details</h2><div class="form-grid">${field('business.legalName','Legal business name')}${field('business.dba','DBA / trade name (optional)')}${field('business.entityType','Business structure','text',['Sole proprietor','LLC','Corporation','Partnership','Other'])}${field('business.formationState','State of formation / registration')}${field('business.address','Business mailing address','textarea')}${field('business.serviceArea','Service area — cities, states, ZIP codes and radius','textarea')}${field('business.contactName','Primary contact name')}${field('business.phone','Business phone','tel')}${field('business.emergencyName','Emergency / dispatch contact')}${field('business.emergencyPhone','Emergency / dispatch phone','tel')}${field('business.availability','Usual availability / scheduling restrictions','textarea')}${field('business.rates','Proposed hourly/day rates, minimums, delivery and overtime (optional)','textarea')}${field('business.website','Business website (optional)','url')}</div>`;}
function equipment(){return `<h2>Equipment</h2>${profile.equipment.map((e,i)=>`<section class="record"><div class="record-heading"><h3>Machine ${String(i+1).padStart(2,'0')}</h3><button type="button" class="text-btn danger" data-remove="equipment:${i}">Remove</button></div><div class="form-grid">${field(`equipment.${i}.make`,'Make')}${field(`equipment.${i}.model`,'Model')}${field(`equipment.${i}.serial`,'Serial number')}${field(`equipment.${i}.ownership`,'Ownership','text',['Owned','Leased','Rented'])}${field(`equipment.${i}.capacity`,'Capacity with attachments (lb)','number')}${field(`equipment.${i}.loadCenter`,'Load center (in)','number')}${field(`equipment.${i}.liftHeight`,'Maximum lift height (ft)','number')}${field(`equipment.${i}.fuel`,'Fuel / power','text',['Diesel','Propane','Electric','Gasoline','Other'])}${field(`equipment.${i}.tires`,'Tires / terrain suitability')}${field(`equipment.${i}.attachments`,'Attachments and configuration (or “None”)')}${field(`equipment.${i}.inspectionDate`,'Most recent inspection date','date')}${field(`equipment.${i}.transport`,'Delivery arrangement','text',['Self-delivery','Third-party hauler','LiftCrew coordination requested'])}${field(`equipment.${i}.transportDetails`,'Hauler / transport details (optional)')}${field(`equipment.${i}.limitations`,'Equipment restrictions (optional)','textarea')}</div></section>`).join('')}<button type="button" class="btn secondary" data-add="equipment">+ Add another machine</button><h2 class="subheading">Operators</h2>${profile.operators.map((o,i)=>`<section class="record"><div class="record-heading"><h3>Operator ${String(i+1).padStart(2,'0')}</h3><button type="button" class="text-btn danger" data-remove="operators:${i}">Remove</button></div><div class="form-grid">${field(`operators.${i}.name`,'Full name')}${field(`operators.${i}.relationship`,'Relationship to your business','text',['Working owner','Employee','Proposed subcontractor'])}${field(`operators.${i}.equipmentTypes`,'Equipment types / classes evaluated')}${field(`operators.${i}.trainer`,'Trainer name / organization')}${field(`operators.${i}.trainingDate`,'Training date','date')}${field(`operators.${i}.evaluationDate`,'Practical evaluation date (within 3 years)','date')}${field(`operators.${i}.evaluator`,'Evaluator name / organization')}${field(`operators.${i}.adult`,'At least 18 years old?','text',['yes','no'])}${field(`operators.${i}.restrictions`,'Work restrictions / refresher training needs (optional)','textarea')}</div></section>`).join('')}<button type="button" class="btn secondary" data-add="operators">+ Add another operator</button>`;}
function insurance(){return `<h2>Insurance</h2><p class="section-link"><a href="/operator-agreement.html" target="_blank" rel="noopener">Coverage requirements ↗</a></p>${coverage.map(([k,label,requirement])=>`<section class="record"><h3>${label}</h3><p class="coverage-min">Proposed requirement · ${requirement}</p><div class="form-grid">${field(`insurance.${k}.carrier`,'Insurance carrier')}${field(`insurance.${k}.policy`,'Policy number')}${field(`insurance.${k}.limit`,'Actual limits / sublimits')}${field(`insurance.${k}.expiry`,'Policy expiration date','date')}</div></section>`).join('')}<div class="form-grid">${field('insurance.brokerName','Broker / agent name')}${field('insurance.brokerEmail','Broker / agent email','email')}${field('insurance.brokerPhone','Broker / agent phone','tel')}${field('insurance.workingOwners','Workers’ compensation: identify covered / excluded working owners','textarea')}${field('insurance.exceptions','Exclusions, deductibles over $10,000, unavailable endorsements and requested exceptions (or “None”)','textarea')}</div><p class="field-hint">Coverage exceptions require LiftCrew approval.</p>`;}
function documents(){return `<h2>Documents</h2><p class="muted">PDF, JPG, PNG or WebP · 10 MB max</p>${documentSlots(profile).map(([kind,id,title,hint],i)=>uploadSlot(kind,id,title,hint,i)).join('')}${uploadSlot('other','','Other supporting documents (optional)','Business licenses, requested exceptions or additional relevant records.','other')}${orphanDocuments()}`;}
function orphanDocuments(){const slots=documentSlots(profile);const orphan=docs.filter(d=>d.active&&!['other','final_agreement'].includes(d.kind)&&!slots.some(([k,id])=>d.kind===k&&d.entity_id===id));return orphan.length?`<section class="upload-slot"><h3>Documents for removed entries</h3><p class="muted">Remove files you no longer need.</p>${orphan.map(d=>`<div class="file-row"><button type="button" class="text-btn file-name" data-download="${d.id}">${h(d.filename)}</button><button type="button" class="text-btn danger" data-delete="${d.id}">Remove</button></div>`).join('')}</section>`:'';}
function uploadSlot(kind,id,title,hint,index){const matched=docs.filter(d=>d.active&&d.kind===kind&&d.entity_id===id);return `<section class="upload-slot"><div class="upload-top"><h3>${h(title)}</h3><span class="tag ${matched.length?'good':''}">${matched.length?'Uploaded':'To upload'}</span></div>${hint?`<details class="upload-help"><summary>Requirements</summary><p>${h(hint)}</p></details>`:''}${matched.map(d=>`<div class="file-row"><button type="button" class="text-btn file-name" data-download="${d.id}">${h(d.filename)}</button><span>${(d.bytes/1024/1024).toFixed(1)} MB${d.expires_on?' · Expires '+h(d.expires_on):''}</span><button type="button" class="text-btn danger" data-delete="${d.id}">Remove</button></div>`).join('')}<div class="upload-inputs"><label class="field"><span>Select document</span><input type="file" data-upload="${index}" data-kind="${kind}" data-entity="${h(id)}" accept=".pdf,.jpg,.jpeg,.png,.webp"></label><label class="field"><span>Document expiry (if applicable)</span><input type="date" id="expiry-${index}"></label><button type="button" class="btn secondary" data-upload-button="${index}">Upload</button></div></section>`;}
function summary(){const b=profile.business;return `<div class="summary-grid"><section><h3>Business</h3><p><strong>${h(b.legalName||'Not entered')}</strong><br>${h(b.contactName)} · ${h(b.phone)}<br>${h(b.address)}</p><p>${h(b.serviceArea)}</p></section><section><h3>Equipment & people</h3><p>${profile.equipment.length} machine(s) · ${profile.operators.length} operator(s)</p><p>${profile.equipment.map(e=>h([e.make,e.model].filter(Boolean).join(' '))).join('<br>')}</p><p>${profile.operators.map(o=>h(o.name)).join('<br>')}</p></section><section><h3>Insurance & documents</h3><p>Broker: ${h(profile.insurance.brokerName||'Not entered')}</p><p>${docs.filter(d=>d.active).length} supporting document(s)</p><p>Exceptions: ${h(profile.insurance.exceptions||'Not entered')}</p></section></div>`;}
function review(){const missing=missingItems(profile,docs),renewals=renewalIssues(profile,docs);return `<h2>Review & submit</h2>${summary()}<details><summary>All application details</summary>${renderRecord(profile)}</details>${missing.length||renewals.length?`<div class="notice error"><strong>${missing.length+renewals.length} item(s) need attention.</strong><ul>${[...missing,...renewals].map(s=>`<li>${h(s)}</li>`).join('')}</ul></div>`:''}<div class="record"><h3>Provider agreement — draft</h3><p><a href="/operator-agreement.html" target="_blank" rel="noopener">Read the full agreement</a> · <a href="/documents/LiftCrew_Provider_Agreement_Draft.pdf" target="_blank" rel="noopener">Download PDF</a> · <a href="/operator-privacy.html" target="_blank" rel="noopener">Privacy notice</a></p><p class="field-hint">${AGREEMENT_VERSION}</p></div>${Object.entries(acknowledgements).map(([k,v])=>`<label class="check"><input type="checkbox" name="ack-${k}" required><span>${h(v)}</span></label>`).join('')}<div class="form-grid"><label class="field"><span>Full legal name · application certification</span><input name="typed-name" required maxlength="200" autocomplete="name"></label><label class="field"><span>Title / authority</span><input name="signer-title" required maxlength="100" placeholder="Owner, authorized manager…"></label></div><button class="btn wide" type="submit" ${missing.length||renewals.length?'disabled':''}>Submit application for review <span aria-hidden="true">→</span></button>`;}
function render(){root.removeAttribute('aria-busy');if(!user||!app){authView();return;}const canEdit=editable(app),renewals=renewalIssues(profile,docs);root.innerHTML=`<div class="account-bar"><span>${h(user.email)}</span><div>${reviewer?'<a href="/operator-review.html">Review applications</a>':''}<button class="text-btn" data-signout>Sign out</button></div></div><div class="portal-heading"><div><h1>Operator application</h1></div><span class="status-badge">${statusLabel[app.status]}</span></div>${notice()}${app.feedback?`<div class="notice"><strong>From LiftCrew</strong><p>${h(app.feedback)}</p></div>`:''}${renewals.length?`<div class="notice error"><strong>Renewal needed — do not accept work relying on expired records.</strong><p>${renewals.map(h).join(' · ')}</p></div>`:''}${canEdit?`<div class="application-layout"><aside class="step-sidebar"><nav aria-label="Application steps">${steps.map((s,i)=>`<button type="button" class="step-link ${step===i?'active':''}" data-step="${i}" ${step===i?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${s}</button>`).join('')}</nav><a href="/operator-agreement.html" target="_blank" rel="noopener">Provider requirements ↗</a></aside><form id="application-form" class="application-card" novalidate>${[business,equipment,insurance,documents,review][step]()}<div class="form-actions"><button type="button" class="text-btn" data-back ${step===0?'disabled':''}>← Back</button><div><span class="save-state">${dirty?'Unsaved changes':'Saved draft'}</span><button type="button" class="btn secondary" data-save>Save draft</button>${step<4?'<button type="button" class="btn" data-next>Save & continue →</button>':''}</div></div></form></div>`:`<section class="application-card status-card"><div class="status-icon" aria-hidden="true">${app.status==='submitted'?'✓':'◇'}</div><h2>${app.status==='submitted'?'Application received.':app.status==='approved'?'Application approved':'Application status'}</h2><p class="lead">${app.status==='submitted'?'Check here for updates.':app.status==='approved'?'Each assignment still requires current records, appropriate coverage, a site assessment and an accepted work order.':'Contact LiftCrew with questions.'}</p>${app.submitted_at?`<p class="muted">Submitted ${h(new Date(app.submitted_at).toLocaleString())} · Revision ${app.revision}</p>`:''}${summary()}<div class="status-actions"><button class="btn secondary" data-print>Print application</button><button class="text-btn" data-refresh>Check for updates</button></div><details><summary>View all submitted details and documents</summary>${renderRecord(profile)}${docs.filter(d=>d.active).map(d=>`<p><button class="text-btn" data-download="${d.id}">${h(d.filename)}</button></p>`).join('')}</details></section>`}`;bind();}
function bind(){
 root.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{set(profile,el.dataset.field,el.value);dirty=true;root.querySelector('.save-state').textContent='Unsaved changes';}));
 root.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>run(async()=>{await save();step=Number(b.dataset.step);render();focusHeading();}));
 root.querySelector('[data-save]')?.addEventListener('click',()=>run(async()=>{await save();message='Draft saved.';render();}));
 root.querySelector('[data-next]')?.addEventListener('click',()=>run(async()=>{await save();step++;render();focusHeading();}));
 root.querySelector('[data-back]')?.addEventListener('click',()=>run(async()=>{await save();step--;render();focusHeading();}));
 root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const key=b.dataset.add;if(profile[key].length>=20){errorMessage='Up to 20 entries are supported. Contact LiftCrew for larger fleets.';render();return;}profile[key].push({id:crypto.randomUUID()});dirty=true;render();});
 root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const [key,index]=b.dataset.remove.split(':');if(!confirm('Remove this entry from your application? Associated uploaded records remain in Documents until removed.'))return;profile[key].splice(Number(index),1);dirty=true;render();});
 root.querySelectorAll('[data-upload-button]').forEach(b=>b.onclick=()=>run(async()=>{const i=b.dataset.uploadButton,input=root.querySelector(`[data-upload="${i}"]`),file=input.files[0];if(!file)throw Error('Choose a file before uploading.');const expiry=root.querySelector(`#expiry-${i}`).value;await save();docs.push(await uploadDocument(app,file,input.dataset.kind,input.dataset.entity,expiry));message='Document uploaded.';render();}));
 root.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>run(()=>downloadDocument(docs.find(d=>d.id===b.dataset.download))));
 root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>run(async()=>{const d=docs.find(d=>d.id===b.dataset.delete);if(!confirm('Remove this document from your current application?'))return;await removeDocument(app,d);docs=docs.filter(x=>x.id!==d.id);message='Document removed from the current application.';render();}));
 root.querySelector('[data-signout]')?.addEventListener('click',()=>run(async()=>{if(dirty)await save();check(await db.auth.signOut());user=null;app=null;docs=[];message='Signed out.';authView();}));
 root.querySelector('[data-refresh]')?.addEventListener('click',()=>run(loadApplication));
 root.querySelector('[data-print]')?.addEventListener('click',()=>{root.querySelector('details').open=true;window.print();});
 root.querySelector('#application-form')?.addEventListener('submit',event=>{event.preventDefault();if(step!==4)return;const f=new FormData(event.target),acks=Object.fromEntries(Object.keys(acknowledgements).map(k=>[k,f.get('ack-'+k)==='on'])),name=String(f.get('typed-name')||'').trim(),title=String(f.get('signer-title')||'').trim();run(async()=>{if(!name||!title||Object.values(acks).some(v=>!v))throw Error('Enter your name and title, and complete every certification.');await save();check(await db.rpc('submit_operator_application',{application_id:app.id,typed_name:name,signer_title:title,acknowledgements:acks}));message='';await loadApplication();});});
}
async function save(){if(!editable(app))return;const result=check(await db.from('operator_applications').update({profile}).eq('id',app.id).eq('status',app.status).select().single());app=result;dirty=false;}
async function run(fn){if(busy)return;busy=true;errorMessage='';message='';const buttons=[...root.querySelectorAll('button')].map(b=>[b,b.disabled]);buttons.forEach(([b])=>b.disabled=true);try{await fn();}catch(e){errorMessage=e.message||'Something went wrong. Please try again.';const alert=root.querySelector('[role=alert]');if(alert){alert.innerHTML=`<p class="notice error">${h(errorMessage)}</p>`;alert.scrollIntoView({behavior:'smooth',block:'center'});}else render();}finally{busy=false;buttons.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled;});if(step===0)root.querySelector('[data-back]')?.setAttribute('disabled','');}}
function focusHeading(){const heading=root.querySelector('.application-card h2');heading?.setAttribute('tabindex','-1');heading?.focus({preventScroll:true});heading?.scrollIntoView({behavior:'smooth',block:'start'});}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recovering=true;user=session?.user;mode='signup';queueMicrotask(authView);}if(event==='SIGNED_OUT'){user=null;app=null;dirty=false;queueMicrotask(authView);}});
try{const {data,error}=await db.auth.getSession();if(error)throw error;if(location.hash.includes('error_description')){const params=new URLSearchParams(location.hash.slice(1));throw Error(params.get('error_description')||'This email link is invalid or expired.');}if(!recovering&&data.session){user=data.session.user;await loadApplication();}else authView();}catch(e){errorMessage=e.message;authView();}finally{root.removeAttribute('aria-busy');}
